spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_HOST}/realms/${OAUTH2_RESOURCESERVER_REALM}
          jwk-set-uri: ${OAUTH2_RESOURCESERVER_HOST}/realms/${OAUTH2_RESOURCESERVER_REALM}/protocol/openid-connect/certs
server:
  port: ${GATEWAY_SERVER_PORT}
securityschema:
  flow:
    tokenUrl: ${OAUTH2_RESOURCESERVER_HOST}/realms/${OAUTH2_RESOURCESERVER_REALM}/protocol/openid-connect/token
    authorizationUrl: ${OAUTH2_RESOURCESERVER_HOST}/realms/${OAUTH2_RESOURCESERVER_REALM}/protocol/openid-connect/auth
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    oauth:
      client-id: ${OAUTH2_CLIENT_ID}
      client-secret: ${OAUTH2_CLIENT_SECRET}
    disable-swagger-default-url: true
    path: /