CREATE TABLE notifications (
	id UUID NOT NULL UNIQUE,
	status SMALLINT NOT NULL,
	type SMALLINT NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	is_array BOOLEAN NOT NULL,
	content TEXT NOT NULL,
	sent_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	CONSTRAINT pk_notifications PRIMARY KEY (id)
);